"""
============================================================
MAPPING PAYS + DONNEES SOCIO-ECONOMIQUES — Carta Pastorale
============================================================
Mapping complet GCatholic → donnees socio-economiques.
~50 pays couverts avec contexte de liberte religieuse.
"""

from typing import Dict, Optional

# Mapping GCatholic (anglais) -> cle standard
GCATHOLIC_TO_STANDARD = {
    "France": "France",
    "Italy": "Italie",
    "United States": "Etats-Unis",
    "Brazil": "Bresil",
    "Nigeria": "Nigeria",
    "Congo, Democratic Republic of the": "RDC",
    "India": "Inde",
    "Philippines": "Philippines",
    "China": "Chine",
    "Mexico": "Mexique",
    "Germany": "Allemagne",
    "Poland": "Pologne",
    "Argentina": "Argentine",
    "Colombia": "Colombie",
    "Venezuela": "Venezuela",
    "Egypt": "Egypte",
    "Ethiopia": "Ethiopie",
    "Kenya": "Kenya",
    "Uganda": "Ouganda",
    "Tanzania": "Tanzanie",
    "Pakistan": "Pakistan",
    "Indonesia": "Indonesie",
    "Vietnam": "Vietnam",
    "Australia": "Australie",
    "Canada": "Canada",
    "Spain": "Espagne",
    "Portugal": "Portugal",
    "Romania": "Roumanie",
    "Ukraine": "Ukraine",
    "Russia": "Russie",
    "Turkey": "Turquie",
    "Iraq": "Irak",
    "Syria": "Syrie",
    "Lebanon": "Liban",
    "South Sudan": "Soudan du Sud",
    "Sudan": "Soudan",
    "Somalia": "Somalie",
    "Afghanistan": "Afghanistan",
    "Korea, South": "Coree du Sud",
    "Japan": "Japon",
    "Thailand": "Thailande",
    "Cuba": "Cuba",
    "Haiti": "Haiti",
    "Guatemala": "Guatemala",
    "Peru": "Perou",
    "Chile": "Chili",
    "Ecuador": "Equateur",
    "Bolivia": "Bolivie",
    "Paraguay": "Paraguay",
    "Uruguay": "Uruguay",
    "Cameroon": "Cameroun",
    "Ivory Coast": "Cote d'Ivoire",
    "Ghana": "Ghana",
    "Madagascar": "Madagascar",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Niger": "Niger",
    "Chad": "Tchad",
    "Central African Republic": "Republique centrafricaine",
    "Sri Lanka": "Sri Lanka",
    "Myanmar": "Myanmar",
    "Bangladesh": "Bangladesh",
    "Nepal": "Nepal",
    "Mongolia": "Mongolie",
    "Kazakhstan": "Kazakhstan",
    "Uzbekistan": "Ouzbekistan",
    "Turkmenistan": "Turkmenistan",
    "Tajikistan": "Tadjikistan",
    "Kyrgyzstan": "Kirghizistan",
    "Georgia": "Georgie",
    "Armenia": "Armenie",
    "Azerbaijan": "Azerbaidjan",
    "Belarus": "Bielorussie",
    "Moldova": "Moldavie",
    "Lithuania": "Lituanie",
    "Latvia": "Lettonie",
    "Estonia": "Estonie",
    "Czech Republic": "Tchequie",
    "Hungary": "Hongrie",
    "Slovakia": "Slovaquie",
    "Slovenia": "Slovenie",
    "Croatia": "Croatie",
    "Bosnia and Herzegovina": "Bosnie-Herzegovine",
    "Serbia": "Serbie",
    "Montenegro": "Montenegro",
    "North Macedonia": "Macedoine du Nord",
    "Albania": "Albanie",
    "Kosovo": "Kosovo",
    "Greece": "Grece",
    "Cyprus": "Chypre",
    "Malta": "Malte",
    "Iceland": "Islande",
    "Ireland": "Irlande",
    "United Kingdom": "Royaume-Uni",
    "Netherlands": "Pays-Bas",
    "Belgium": "Belgique",
    "Luxembourg": "Luxembourg",
    "Switzerland": "Suisse",
    "Austria": "Autriche",
    "Denmark": "Danemark",
    "Sweden": "Suede",
    "Norway": "Norvege",
    "Finland": "Finlande",
}

def get_pays_data(gcatholic_name: str) -> dict:
    """Recupere les donnees d'un pays a partir de son nom GCatholic."""
    standard_name = GCATHOLIC_TO_STANDARD.get(gcatholic_name, gcatholic_name)
    return DONNEES_PAYS.get(standard_name, {
        "idh": None, "pib_par_habitant_usd": None, "taux_pauvrete": None,
        "taux_urbanisation": None, "indice_liberte_religion": "inconnu",
        "score_persecution": None, "population_totale": None,
        "contexte_liberte": "Donnees non disponibles pour ce pays.",
        "defis_specifiques": [],
        "continent": "Inconnu",
    })